### ISSUE TITLE
Fix the definition of the sequence operator

### ISSUE THREAD

**Issue by foretspaisibles** [michipili/lemonade#7]
The [definition](https://github.com/michipili/lemonade/blob/master/ppx/ppx_lemonade.ml#L274-L277) should be independent of Lwt.

**Comment by gasche** [comment]
If I understand the ppx code correctly (I justed skimmed over it), `>>` is transformed globally even outside any lemonade-specific extension point that would denote the different interpretation. Giving a semantics to a valid OCaml operator is very fishy and I would recommend against it.

**Comment by foretspaisibles** [comment]
This is a good point. Do you have any suggestion for a method to delimit the replacement? Would something like

```
 [%lemonade $expr$]
```

or

```
begin%lemonade
  $expr
end
```

look like a reasonable choice?

**Comment by gasche** [comment]
Fine by me -- but I'm not an user of the extension. I guess the Lwt people asked themselves the same questions (and decided to be naughty). @Drup, any opinion?

**Comment by Drup** [comment]
I don't decided to be naughty, I decided to be retro-compatible with the camlp4 version. :)

Imho, just remove this thing. It shouldn't exist.

**Comment by foretspaisibles** [comment]
> Imho, just remove this thing. It shouldn't exist.

This also would be a valid option. :)
